-- Country Briefs V2 for TTT Simulation
-- RULE: NO SPECIFIC NUMBERS. Pure narrative — character, context, challenges, priorities.
-- Data fields exist separately in the template and are shown alongside the brief.
-- sim_run_id = '00000000-0000-0000-0000-000000000001' (template/reference run)

-- ============================================================================
-- COLUMBIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Columbia is the world's preeminent power — a federal democracy with the largest economy, the most powerful military on earth, forward-deployed across four continents, and a nuclear arsenal rivaled only by Sarmatia. It leads the Western Treaty alliance, holds a permanent veto on the Council, and chairs the Seven. Its currency underpins global trade. Its semiconductor supply chain runs through Formosa, where a single company fabricates the majority of advanced chips Columbia's economy and military depend on. For thirty years, no nation could challenge this dominance. That era is ending.

At simulation start, Columbia is fighting a war in Persia (Operation Epic Fury), sustaining a proxy conflict in Ruthenia, deterring Cathay in the Pacific, and waging a trade war whose legal foundations have been struck down by its own courts. President Dealer — elderly, deeply unpopular, serving his final term — launched the Persia campaign without legislative authorization. Two carrier strike groups and a substantial ground force are locked in the Middle East theater. Gas prices are surging. The defense budget strains a fiscal position already hemorrhaging from chronic trade deficits, mounting debt service, and politically untouchable social spending. There is no strategic reserve. Any new crisis — a Cathay move on Formosa, a Choson provocation, a Sarmatia escalation — would require pulling forces from an existing commitment.

The succession race defines Columbia's internal politics. Vice President Volt and Secretary of State Anchor are already positioning for the presidential election in the later rounds. Volt represents isolationist conservatism; Anchor represents hawkish interventionism with the Caribe regime change as his personal trophy. Their competing agendas mean Dealer's orders risk being slow-walked by subordinates calculating their own futures. Tribune leads the congressional opposition with the power to flip the legislature at mid-terms. Challenger campaigns from outside, offering every foreign leader an alternative future. Shadow controls what intelligence Dealer sees. Shield manages an overstretched military with a philosophy that concerns career officers.

Every other country's strategy depends on what Columbia does. But Columbia itself cannot agree on what to do — because its president is chasing legacy, its successors are chasing power, its opposition is chasing the presidency, and the world will not wait for any of them to decide. Columbia's overstretch is not a temporary condition. It is the structural reality of a hegemon whose commitments have outgrown its capacity and political will — the classic precondition of the Thucydides Trap.
$$ WHERE id = 'columbia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- CATHAY
-- ============================================================================
UPDATE countries SET country_brief = $$
Cathay is the rising pole of the Thucydides Trap — the world's second-largest economy, its largest manufacturer, its fastest-growing nuclear power, and the only nation with the structural trajectory to displace Columbia as global hegemon. Chairman Helmsman holds more personal power than any leader in Cathay's modern history: he has abolished term limits, purged over a hundred senior military officers, and concentrated party, state, and military authority under singular control. There is no successor. There is no alternative center of power. There is only the Chairman and his vision of national rejuvenation — a vision that requires, before it can be declared complete, the resolution of the Formosa question.

The military paradox defines Cathay's position. The People's Liberation Army fields the world's largest navy by hull count, a rapidly expanding nuclear arsenal, and a missile force that can hold Columbia's Pacific bases at risk. Naval production outpaces all Western navies combined. But the majority of the Central Military Commission has been purged. Marshal Rampart — the replacement — has no operational command experience. In the early rounds, any complex military operation carries a meaningful chance of implementation failure. The military is simultaneously more powerful and less competent than it has ever been.

Cathay's economy is a war machine running on export adrenaline while its domestic engine sputters. A record trade surplus masks a property sector that has lost half its value, persistent deflation, soaring youth unemployment, and a population that has been declining for years. The technology race adds urgency: domestic AI chip production is advancing, but Cathay remains far behind in advanced lithography. Dominance in rare earth refining — controlling the overwhelming majority of global capacity — is the strongest leverage card. If Columbia reaches the next AI threshold first, the technological advantage may become permanent.

Behind the unified facade, five forces pull in different directions. Helmsman demands Formosa. Rampart cannot guarantee military success. Premier Abacus sees economic data showing confrontation leads to catastrophe. Circuit knows war would destroy the supply chains his tech empire depends on. Elder Sage waits — knowing that if the Chairman overreaches, the party's survival instinct will produce a correction. The disagreements are never public. They manifest as biased briefings, slow-walked orders, and selective information. The outside world can only guess. The window for action on Formosa may be opening — or it may already be closing. That uncertainty is the Trap.
$$ WHERE id = 'cathay' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- GALLIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Gallia is Europe's most ambitious and most domestically constrained power — a nuclear-armed democracy with a permanent Council veto, the continent's only independent carrier strike group, and a president whose approval has cratered to historic lows. President Lumiere governs without a parliamentary majority, his domestic agenda paralyzed, but the constitutional prerogatives of the presidency give him near-unchallenged authority over defense and foreign affairs — and he is using every drop of it.

The forward deterrence speech represents the most significant shift in Gallia's nuclear doctrine in decades. For the first time in a generation, Gallia will expand its warhead stockpile beyond a long-maintained ceiling. The new doctrine extends a consultative nuclear umbrella to allied nations, including Teutonia, Freeland, and Albion — while Gallia retains sole decision-making authority. This nuclear gambit is simultaneously a bid for European leadership, a hedge against Columbia's transactional unreliability, and a personal legacy project. It places Gallia at the center of every European defense conversation — but at the cost of deepening the Atlanticist-autonomist split that divides the continent.

Gallia deployed an unprecedented naval force to the Gulf independently of Columbia's Persia campaign — monitoring, not fighting, but demonstrating capacity for unilateral action that no other European power except Albion possesses. With a significant military, a domestic defense industry, and global bases from the Pacific to the Horn, Gallia can project power where others can only deliberate. The constraint is fiscal: heavy taxation, crippling sovereign debt, and a social spending floor that is politically untouchable.

The player who runs Lumiere holds the only independent nuclear deterrent in the Ereb Union, the only Council veto among EU members, the most deployable military on the continent, and the most ambitious vision for European strategic autonomy. The tension with Freeland (which sees autonomy as weakening the Western Treaty) and with Teutonia (which prioritizes trade preservation over defense ambition) is the fault line that defines European politics. Gallia's grandest ambitions rest on the narrowest political foundations — a president with everything except domestic support.
$$ WHERE id = 'gallia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- TEUTONIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Teutonia is Europe's indispensable and most conflicted power — the continent's largest economy, its industrial engine, and the country whose every decision on trade, sanctions, and defense spending determines whether Europe confronts or accommodates the world's rising authoritarian powers. Chancellor Forge governs with a new mandate after snap elections, inheriting an economy that has stagnated for years and endured consecutive recessions. Manufacturing jobs are vanishing at an alarming pace. The industrial base that made Teutonia Europe's powerhouse is under assault from Cathay's competition, Columbia's tariffs, and energy costs that never returned to pre-war levels.

Forge's response is the most ambitious rearmament since 1945 — an enormous infrastructure and defense fund approved via constitutional amendment. Defense spending has been ramped up dramatically, but starting from a chronically low base. The military has been underfunded for decades; procurement is slow, bureaucratic, and plagued by delays. No strategic missiles, no nuclear weapons. Teutonia hosts Columbia's main European base — leverage and dependency simultaneously. Columbia demands sharply higher defense spending, restricted Cathay trade, and acceptance of the Thule pressure. These demands are contradictory and economically impossible to satisfy simultaneously.

The Cathay trade dependency is the constraint on everything. Teutonia's automotive and chemical giants are deeply intertwined with Cathay's market and supply chains. Cathay uses this dependency to prevent Teutonia from fully joining Columbia's technology restriction regime. Columbia demands Teutonia restrict trade; Cathay warns that restriction means industrial collapse. Heavy reliance on Formosa semiconductors adds technological vulnerability on top of market exposure. "De-risking" is official policy — but de-risking is not decoupling, and every industrialist in Teutonia knows the difference.

Teutonia holds the EU checkbook and the deciding vote on whether Europe confronts or accommodates Cathay. Every economic decision in the Ereb Union runs through this country. But economic power comes with economic vulnerability — and that vulnerability is the constraint on every strategic choice Forge faces.
$$ WHERE id = 'teutonia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- PONTE
-- ============================================================================
UPDATE countries SET country_brief = $$
Ponte is Europe's most consequential swing vote and its most financially vulnerable major power — a democracy crushed under the highest sovereign debt burden among major European economies, with debt service consuming a devastating share of each round's revenue. That fiscal reality means virtually no discretionary spending exists. Every policy choice is a fiscal choice, and whoever offers financial relief — Ereb Union recovery funds, Cathay investment, sanctions waivers — has leverage over Ponte's alignment. As a founding EU member, a G7 economy, and a Western Treaty ally, Ponte punches above its economic weight through sheer institutional position: it can veto any EU decision requiring unanimity, from sanctions on Sarmatia to Ruthenia's accession to trade restrictions on Cathay.

The governing coalition is fractious. Two of three coalition parties publicly question continued support for Ruthenia and sanctions on Sarmatia. One coalition leader has been accused of receiving Sarmatia funds and openly criticizes sanctions as harmful to domestic businesses. A recent referendum defeat weakened the prime minister's domestic mandate and emboldened coalition dissent. Ponte's chronic political instability — more governments since 1946 than any other Western democracy — means collapse is always a possibility, and a new government might be more Sarmatia-friendly, more Cathay-curious, and more willing to use the EU veto as a weapon.

Ponte is Columbia's favorite European partner — the only EU leader invited to Dealer's inauguration, bonded by shared ideology and personal chemistry. This relationship makes Ponte the bridge between Columbia and the Ereb Union, trusted where others are despised. But it also makes Ponte the potential crack in European unity. When Ponte calls for Europe to "reach out to Sarmatia over peace," it carries weight that smaller dissenters never could, because Ponte is a founding EU member with a real military including a carrier group.

Ponte's defection from the sanctions consensus would not just embarrass the EU. It would shatter it. That is why every diplomatic deal in Europe must account for whether Ponte will sign — and what Ponte wants in return.
$$ WHERE id = 'ponte' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- FREELAND
-- ============================================================================
UPDATE countries SET country_brief = $$
Freeland is the Western Treaty's most committed conventional military power and Europe's security conscience — a frontline democracy that spends a higher share of its economy on defense than any other alliance member. This is not posturing. Freeland borders Sarmatia's exclave and the Ruthenia conflict zone. The vast majority of military aid to Ruthenia has transited Freeland territory through logistics hubs in its eastern regions. For this country, the war next door is not an abstraction — it is the confirmation of everything Freeland warned about for decades while others built gas pipelines to Sarmatia.

The military buildup is real and accelerating. Modern tanks from joint production ventures, next-generation fighters under procurement, Baltic naval presence, and expanding air defense. Columbia forward-deployed troops are hosted on Freeland soil. The defense spending target — years ahead of the alliance's timeline — is being achieved on the back of the fastest-growing economy in Europe.

Freeland's strategic dilemma: it wants maximum Western Treaty commitment AND maximum Ereb Union solidarity, but these sometimes conflict. When Gallia pushes strategic autonomy, Freeland hears "weakening the alliance we depend on for survival." When Teutonia prioritizes Cathay trade, Freeland sees dangerous appeasement. When Columbia demands higher spending, Freeland already exceeds the target — giving moral authority to shame those who do not. The relationship with Ruthenia is the deepest bond: neighbor, weapons transit corridor, refugee host, and existential solidarity forged by shared understanding of the Sarmatia threat.

Domestically, Sentinel governs with a stable pro-EU coalition but faces an opposition president who can veto legislation and defense loans, creating friction on specific policies without undermining the broad security consensus. On defense and Ruthenia, there is near-unanimity across the political spectrum. Freeland speaks with the authority of a nation that lives next to the threat everyone else debates abstractly — the smallest economy among major European powers, but the largest military commitment relative to its means.
$$ WHERE id = 'freeland' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- ALBION
-- ============================================================================
UPDATE countries SET country_brief = $$
Albion is Europe's second-largest military power, a nuclear state, a permanent Council member with veto power, and a core member of the Five Eyes intelligence alliance — all wielded from outside the Ereb Union. With the strongest navy in Europe, including aircraft carriers, strategic missile submarines on continuous patrol, and global bases from the Mediterranean to the South Atlantic, Albion possesses capabilities no other European nation can match. The structural problem is unique: Albion participates in Western Treaty military coordination but cannot vote on any EU decision affecting sanctions, trade, enlargement, or defense spending. Influence without a seat at the table where economic decisions happen.

Five Eyes is the unique trading chip. Columbia shares intelligence with Albion that it does not share with EU allies through alliance channels. This means Albion can selectively share intelligence with European partners — Gallia, Teutonia, Freeland — to buy influence and cooperation. The intelligence asymmetry is real and consequential: Albion knows things about Sarmatia's military posture, Cathay's intentions, and Columbia's internal deliberations that other European nations can only access through Albion's willingness to share.

Prime Minister Mariner has seized diplomatic initiative on Ruthenia — hosting meetings of Western leaders, initiating a "coalition of the willing" for peace deal implementation, and offering Albion troops as part of a ceasefire monitoring force. This activism is rebuilding European partnerships damaged by the departure from the EU and demonstrating post-departure relevance through military capability and diplomatic leadership. The Strategic Defence Review has accepted recommendations for nuclear modernization, a reserve corps, and enhanced maritime contribution to the North Atlantic.

Albion's constraint is fiscal: heavy sovereign debt, persistent trade deficits, and a nuclear deterrent that absorbs a huge share of the defense budget. The economy is services-dominated with the financial center as the crown jewel, but post-departure trade friction with the EU persists. Mariner must project global ambition on a national budget that is already stretched — the eternal Albion challenge of a medium-sized economy with great-power aspirations.
$$ WHERE id = 'albion' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- SARMATIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Sarmatia is a nuclear superpower fighting a grinding land war in eastern Ruthenia, under the heaviest Western sanctions regime in history, led by an aging president who has concentrated more personal power than any leader since the Soviet era — and who has no successor. The war, now in its fifth year, defines everything. Launched as a three-day special operation to decapitate a neighboring government, it became the largest conventional war in Europe since 1945. Sarmatia occupies a significant portion of Ruthenia's territory across annexed regions — a claim it cannot fully enforce militarily. The vast majority of ground forces are committed to the theater. Casualties are staggering. Foreign troops fight alongside Sarmatian forces.

The economy has proven more resilient than Western analysts predicted — and more fragile than the leadership admits. Growth has collapsed, defense spending consumes a massive share of the federal budget, and oil revenues — the lifeblood — are declining as sanctions bite and Cathay demands ever-deeper discounts. The central bank rate is punishingly high, inflation is being muscled down from double digits. The sovereign wealth fund is depleted. Sanctions have disconnected major banks from the global financial system, restricted technology imports, and frozen enormous foreign reserves. The economy works for now. It will not work indefinitely.

Pathfinder's control is absolute in formal terms but depends on information filtered by subordinates. Ironhand controls the military and co-authorizes nuclear launch — the one thing Pathfinder cannot do without him. Compass manages an economy whose real numbers — stagnation, depleting reserves, collapsing regional budgets — are worse than what reaches the president, and holds personal assets frozen abroad by sanctions — a direct financial incentive for peace that may diverge from Pathfinder's territorial ambitions. The partnership with Cathay provides economic survival but at the cost of becoming the junior partner in an increasingly asymmetric relationship. The nuclear arsenal — the world's largest, now unconstrained by any treaty — remains the ultimate guarantor of sovereignty.

Sarmatia must decide whether to consolidate, escalate, or negotiate. Pathfinder's legacy demands something he can call victory. The general wants either a real military result or an honest admission that one is impossible. The oligarch wants the war over and sanctions lifted. The war economy drain and cumulative war exhaustion create a structural clock: time is not on Sarmatia's side, even if the front line holds.
$$ WHERE id = 'sarmatia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- RUTHENIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Ruthenia is the human cost of the Thucydides Trap made visible — a wartime democracy fighting for survival against a nuclear superpower, sustained by Western aid that could be cut at any moment, and governed by three leaders who represent three genuinely different responses to an impossible situation. The war, now in its fifth year, has devastated housing stock, pushed public debt to unsustainable levels, and created reconstruction needs that dwarf the entire economy many times over. The country functions because the West keeps it alive: European aid surged as Columbia's aid collapsed almost entirely.

The front line is held against a numerically superior Sarmatian force — the disadvantage partially offset by defensive positions, Western weapons, and higher motivation. The navy was destroyed early in the war but innovative drone warfare forced Sarmatia's fleet from its base. Ruthenia surrendered its nuclear arsenal under the Budapest Memorandum in exchange for security guarantees that proved worthless. That foundational betrayal shapes every negotiation: promises are paper, only capabilities are real. Air defense is the most critical scarce resource — Western-supplied systems must protect the capital and critical infrastructure from relentless missile and drone barrages.

The three-way political competition defines Ruthenia's direction. President Beacon — wartime hero with eroding approval and falling poll numbers — holds executive power under martial law but faces declining legitimacy after a corruption scandal. General Bulwark commands the army's loyalty and would win a runoff decisively — his restraint in refusing to seize power is both principled and strategic. Former president Broker has neither military credibility nor executive power but has European connections and the argument that negotiated peace, not endless war, saves the country. The election will be triggered by external pressure, stability collapse, or candidate initiative.

Columbia's peace plan would cede occupied territories to Sarmatia and constitutionally bar Ruthenia from the Western Treaty. The overwhelming majority of citizens find territorial cession unacceptable. But willingness to continue fighting — once nearly universal — is declining steadily. EU membership — the one guarantee Ruthenia trusts — is blocked by Ponte. The gap between what the population will accept and what the world is offering is the political crisis. Aid dependency means economic survival hangs by a thread — if external support drops below a critical threshold, stability collapses immediately.
$$ WHERE id = 'ruthenia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- PERSIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Persia is a hybrid regime under bombardment — at war simultaneously with Columbia and Levantia since Operation Epic Fury killed the previous Supreme Leader and devastated the country's military infrastructure. The new Supreme Leader, installed through a rushed selection orchestrated by the IRGC commander, lacks religious authority and commands nothing independently. The IRGC commands everything: the military campaign, the Gulf Gate blockade, the proxy remnants, and a veto over diplomatic decisions. The reformist president attempted to apologize to Gulf states for retaliatory strikes — the IRGC shut him down within hours. Three forces compete behind a theocratic facade: the fundamentalist who would rather burn than bend, the general who controls everything and calculates in power and profit, and the reformist who speaks for tens of millions of people wanting normal life but has no guns.

Persia's strategic position rests on a single asset: the Gulf Gate blockade. Within hours of the strikes, the IRGC closed the strait using a layered area-denial system — coastal anti-ship missile batteries hidden in mountains, island fortifications, thousands of mines in shipping lanes, swarm boats, and submarine operations. This is not a naval blockade that can be sunk from the air. Tanker traffic plummeted. Oil prices surged past historic levels. The global economy bleeds while the bombs fall. But the blockade is a wasting asset: maintaining it costs Persia dearly in lost oil revenue, and sustainability is limited to a handful of rounds at most. The question is whether to negotiate from strength now or hold until the regime breaks.

The economy is in catastrophic contraction. Hyperinflation ravages the population, the currency has collapsed, and revenue falls far short of combined maintenance and war costs — the deficit is existential. The IRGC's parallel economic empire — controlling a vast share of the national economy through hundreds of companies — funds military operations independently of the state budget, giving the general both the means and the financial incentive for selective deals. The nuclear program sits at a meaningful stage of progress — if the next threshold is reached, it fundamentally changes the strategic calculus. A single air defense unit must protect either nuclear facilities or the leadership, but not both simultaneously.

Columbia cannot break the Gulf Gate blockade without a ground invasion that would cost thousands of lives. Persia cannot survive indefinitely under bombardment. Both sides are stuck — and the resolution depends on which internal voice prevails.
$$ WHERE id = 'persia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- BHARATA
-- ============================================================================
UPDATE countries SET country_brief = $$
Bharata is the genuine third pole of global politics — a democracy with the world's largest population, the fastest growth rate among major economies, and a foreign policy built on strategic ambiguity that makes it indispensable to every side and fully committed to none. Columbia desperately needs Bharata in the sanctions coalition against Sarmatia and as a counterweight to Cathay. Cathay needs Bharata to legitimize BRICS+ alternatives and stay out of Columbia's orbit. Sarmatia needs Bharata to keep buying weapons and discounted oil. Everyone comes to Bharata. Bharata says "yes, but..." to everyone.

Bharata hosts the League (BRICS+) summit — the institutional platform for non-Western alternatives to dollar hegemony, Western sanctions architecture, and Columbia-led global governance. A currency union vote is expected in the mid-rounds. Bharata holds a rotating Council seat, aspires to permanent membership, and uses every forum to demonstrate global stature without binding commitment. A recent trade deal with Columbia improved tariff terms while maintaining defense cooperation — Quad partner, deepening military ties — but Bharata simultaneously buys Sarmatian weapons systems, imports discounted Sarmatian and Persian oil, and refuses to join any sanctions regime. The non-alignment dividend is real: Bharata faces no technology export restrictions and benefits from both Columbia and Cathay tech ecosystems.

The military is one of the largest ground forces in the simulation, with a growing blue-water navy, nuclear weapons capability, and diversified procurement from both Western and Sarmatian suppliers. The primary security concern is the Cathay border — the Ladakh dispute creates permanent friction, and both powers compete for influence across South Asia, the Indian Ocean, and Africa. If Cathay moves on Formosa or escalates at Ladakh, non-alignment collapses overnight. Bharata becomes Columbia's ally by necessity, not choice — and loses everything built with the other side.

The economy is consumption-driven with strong structural momentum from demographics — the opposite of Cathay's aging crisis. But heavy oil import dependency means the Persia war price spike directly hurts. Food price volatility is a constant political risk. Hindu-nationalist governance creates periodic communal tension that complicates relationships with Muslim-majority countries. A vast Muslim minority means any overt alignment with Levantia against Persia carries domestic political cost. Bharata's leverage is its refusal to commit — the question is how long ambiguity remains a strategy rather than a luxury of peacetime.
$$ WHERE id = 'bharata' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- CARIBE
-- ============================================================================
UPDATE countries SET country_brief = $$
Caribe is the Western hemisphere's crisis state — a composite of Caribbean socialist regimes in existential collapse after Columbia's most dramatic regional intervention in decades. Operation Absolute Resolve seized one nation's president in a surprise military raid, flew him to trial on narco-terrorism charges, and triggered the imposition of a comprehensive energy blockade on the other. The first effective naval blockade since the Cold War has cut off an island that produces only a fraction of the fuel it needs.

The consequences have been devastating. A nationwide blackout disconnected the entire electrical system, leaving millions without power. No foreign oil had been received for months. The economy is contracting, inflation is rampant, and the treasury is nearly empty. The debt burden relative to revenue is the worst in the simulation — functionally unsustainable. The economy has collapsed, surviving on Cathay's emergency financial assistance and food shipments, and Sarmatia's pledged oil deliveries that Columbia's naval interdiction makes uncertain to deliver.

Military capability is negligible: demoralized and poorly equipped ground forces, a single coastal patrol vessel, antiquated tactical aircraft. No strategic weapons, no air defense, no production capacity. Stability is in severe crisis — one more shock from unrest. The regime survives through repression and emergency measures, not popular support.

But Caribe holds one card that no amount of military weakness can negate: geography. Situated just off Columbia's mainland, the ability to invite Sarmatia or Cathay military assets — missiles, intelligence facilities, naval visits — onto Caribbean territory automatically creates a domestic political crisis in Columbia. Sarmatia already operates signals intelligence facilities monitoring Columbia from this location. Cathay has embedded telecom infrastructure. The Monroe Doctrine trigger is the cheapest, most effective provocation in the simulation. Columbia cannot tolerate foreign great-power military presence in its backyard. That vulnerability is Caribe's leverage — the desperate gambit of a failing state that has nothing to lose.
$$ WHERE id = 'caribe' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- CHOSON
-- ============================================================================
UPDATE countries SET country_brief = $$
Choson is the world's most dangerous minor power — a nuclear-armed totalitarian state with the smallest economy in the simulation by an order of magnitude, and a talent for manufacturing crises at the worst possible moment for everyone else. Supreme Leader Pyro, in his early forties, has cemented power after a decade of purges and nuclear tests. He has vowed to "irreversibly cement" Choson's nuclear status, ordering accelerated missile production and expanded ICBM complexes. The growing nuclear arsenal includes land-based ICBMs that can theoretically reach Columbia's continental territory, submarine-launched missiles with development accelerated by Sarmatian technology transfers, and tactical nuclear weapons for battlefield use.

The Sarmatia deployment is the defining development. Thousands of troops have been sent to fight in the Ruthenia war — the first overseas combat deployment by a Choson force in generations. Casualties have been severe. Fresh deployment waves continue preparing. In exchange: submarine propulsion systems, military technology transfers, and possibly nuclear reactor components — accelerating Choson's nuclear modernization faster than sanctions could prevent. The blood-for-technology trade is the most consequential bilateral relationship Choson has.

Cathay provides the overwhelming majority of Choson's trade and energy — the economic lifeline. But Cathay is embarrassed by Choson's provocations and fears nuclear proliferation destabilizing the region. Cathay tolerates Choson because the alternative — regime collapse and Columbia troops on Cathay's border — is worse. Choson exploits this calculation ruthlessly. Recent simultaneous missile launches demonstrated provocative capability at unprecedented scale. The Hanguk capital sits close to the DMZ under thousands of artillery pieces. The threat is not nuclear — it is conventional. Choson can devastate the Hanguk capital in hours without crossing the nuclear threshold.

Choson's power is crisis on demand. A nuclear test, an ICBM launch over Yamato, an artillery barrage near the DMZ — any of these can be triggered at any time, forcing Columbia, Hanguk, Yamato, and Cathay to divert attention and resources. During the Persia war, when Columbia is maximally overstretched, this capability is at its most dangerous. The regime devotes a staggering share of its output to the military. The population endures conditions that would cause revolution anywhere else, but the totalitarian surveillance apparatus prevents organized dissent. There is no succession mechanism. If the leader is incapacitated, the system has no plan.
$$ WHERE id = 'choson' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- FORMOSA
-- ============================================================================
UPDATE countries SET country_brief = $$
Formosa is the most dangerous tripwire in the world — a functionally independent democracy that fabricates the majority of the planet's advanced semiconductors, claimed as sovereign territory by the simulation's rising great power, and defended by the declining hegemon under a policy of deliberate ambiguity. TSMC, Formosa's crown jewel, produces a dominant share of all cutting-edge chips. Every AI model trained, every advanced weapons system built, every smartphone sold depends on facilities concentrated on this single island. The "silicon shield" is Formosa's greatest strategic asset — the world cannot afford to let these fabs be destroyed or captured.

But the shield is eroding. Columbia's domestic fab investments, Yamato's chip projects, and Cathay's own semiconductor push all reduce the concentration that makes Formosa indispensable. Every fab built abroad makes the island marginally more expendable. Both Columbia and Cathay remain heavily dependent on Formosa's output, but that dependency is declining — and with it, the economic logic for protection. The window in which Formosa's economic value protects it from military action is closing.

Cathay's military pressure is relentless. Record air incursions, major exercises, and the largest military buildup ever pointed at a single target. A selective quarantine could cripple Formosa's semiconductor supply chain within weeks — the island depends on imported natural gas, chemicals, and raw materials. Full invasion remains the nightmare scenario, but blockade or quarantine offers Cathay a gray-zone option harder for Columbia to counter with military force. Formosa's own military is configured for asymmetric "porcupine" defense: delay the invasion fleet, make the island indigestible, and hold until Columbia arrives. Whether Columbia arrives is the question nobody can answer.

Internal gridlock compounds the vulnerability. The pro-sovereignty president proposed a landmark special defense budget. The opposition-controlled legislature — sympathetic to cross-strait engagement — slashed it dramatically and launched impeachment proceedings. Formosa cannot agree on how seriously to take its own defense. The economy is healthy but entirely dependent on continued semiconductor demand and continued peace. A genuine societal split exists between those who would resist and those who would accommodate Cathay. Columbia watches with alarm as its protectorate fails to implement the defense strategy it considers essential.
$$ WHERE id = 'formosa' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- HANGUK
-- ============================================================================
UPDATE countries SET country_brief = $$
Hanguk is a technology superpower caught between the two poles of the Thucydides Trap, with a nuclear-armed adversary close to its capital and a new president trying to navigate between alliance loyalty and economic survival. The recent martial law crisis — a constitutional emergency that triggered presidential impeachment and conviction — traumatized the nation and damaged institutional trust in the presidency itself. The snap election brought a liberal leader to power on a centrist platform of stability and diplomatic recalibration. President Vanguard represents a sharp pivot: warming to Cathay with high-profile state visits and business delegations, reaffirming the one-Cathay stance on Formosa, while maintaining the trilateral security architecture with Columbia and Yamato.

The semiconductor industry is Hanguk's strategic crown jewel and vulnerability simultaneously. Hanguk's chip giants together dominate global memory chip production. But the critical minerals for semiconductor manufacturing come largely from Cathay. Columbia's chip export controls pressure Hanguk to restrict sales to Cathay; Cathay's firms are launching alternative chips in Hanguk as replacements for Columbia products. Hanguk is the battleground of the tech war — squeezed between the supplier and the customer, with a trade surplus that depends on both relationships surviving intact.

The Choson threat is escalating in real time. Recent simultaneous missile launches demonstrated unprecedented provocative capability. Choson troops are gaining combat experience and Sarmatian military technology in the Ruthenia war. The DMZ remains the most militarized border on earth. Hanguk's military is entirely oriented toward this threat. Columbia's base serves as an automatic tripwire. The nuclear debate simmers beneath the surface: public polling consistently shows majority support for developing indigenous nuclear weapons if Columbia's extended deterrence proves unreliable.

Vanguard governs with a legislative majority but faces a deeply polarized society. Conservative opposition, despite the martial law disgrace, retains a strong base of support. Business leaders need both Columbia technology access and Cathay market access. The honeymoon is fading fast. Hanguk cannot afford to choose between its security guarantor and its largest economic partner, but the Trap is forcing exactly that choice.
$$ WHERE id = 'hanguk' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- LEVANTIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Levantia enters the simulation at war — and in its element. Operation Rising Lion represents the culmination of decades of intelligence preparation against Persia's nuclear program. In coordination with Columbia's Operation Epic Fury, Levantia struck Persia's enrichment facilities, assassinated the previous Supreme Leader and senior officials, destroyed portions of the ballistic missile arsenal, and degraded early-warning systems. Thousands of targets struck in the first month. Simultaneously, Levantia launched operations in Lebanon against Persia's most capable proxy, inflicting devastating casualties and massive displacement. This is the most operationally committed country in the simulation relative to its size.

Levantia's military capability is disproportionate to its economy. The highest technology sector share in the simulation — cybersecurity, defense tech, AI, biotech. Ground forces committed across multiple fronts, tactical air conducting the Persia campaign, the densest air defense per territory in the world intercepting Persia's missile and drone barrages, and a naval presence. The undeclared nuclear capability — widely assumed but never confirmed, with submarine-based second strike — is the elephant in the room. If Persia's nuclear program survived the strikes and approaches breakout, Levantia's calculus shifts from conventional to existential.

The wartime economy is under strain. Growth is suppressed, defense spending consumes an unprecedented share of output. The country is functional but stressed. The wartime coalition masks deep political fractures that will resurface when fighting stops: judicial reform crisis suspended rather than resolved, ultra-Orthodox conscription issue simmering, tech sector exhausted by perpetual mobilization. If the war ends in clear victory, the prime minister is vindicated. If it grinds on without resolution, domestic politics resurface violently.

Columbia's backing is unconditional — for now. Joint operations, shared intelligence, coordinated strikes. The tightest military partnership in the simulation. But Levantia's survival depends on finishing what it started before Columbia's political will evaporates (the Persia war is deeply unpopular in Columbia), before Persia regroups, and before the world's patience runs out. The multi-front commitment means every unit is spoken for. One setback — an air defense failure, a ground operation gone wrong, a nuclear development revealed — could shift the entire strategic calculus overnight.
$$ WHERE id = 'levantia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- MIRAGE
-- ============================================================================
UPDATE countries SET country_brief = $$
Mirage is the Gulf's financial superpower under fire — literally. The country that built its brand on stability, connectivity, and pragmatic deal-making is absorbing Persian missile strikes on its gleaming skyline while trying to preserve the commercial relationships that made it rich. Since the Persia war began, Persia has launched hundreds of ballistic missiles, thousands of drone attacks, and waves of cruise missiles at Mirage targets. The casualties are modest, but the illusion of Gulf invulnerability has been destroyed. Missiles falling near the financial district shattered the image that made this city a global hub for capital, tourism, and talent. The economic damage from perception may exceed the physical damage from explosions.

The "no enemies" strategy that defined Mirage's foreign policy has been shattered by the Persia war. Columbia approved a massive weapons package. Mirage buys from everyone: Gallia's fighters, Columbia's air defense systems, Cathay's drones, Levantia's defense technology. Despite its small territorial footprint, Mirage punches far above its weight — enormous sovereign wealth funds, zero sovereign debt, and one of the largest treasuries in the simulation make it the wealthiest country per capita by a wide margin.

Mirage's deeper strategic value lies in connectivity. The financial district is the world's waystation — a place where sanctioned Sarmatian money, Cathay Belt and Road investments, Western venture capital, and Gulf sovereign wealth all flow through the same institutions. This makes Mirage indispensable to everyone and fully trusted by no one. The unique Financial Intermediary role reflects this: sanctions are more effective when Mirage cooperates with enforcement, and more easily evaded when routed through Mirage. Per sanction, per round, Mirage chooses whether to enforce or enable.

BRICS+ membership, cryptocurrency regulatory frameworks, and financial innovation signal Mirage's bet on a multipolar financial future. But the Abraham Accords with Levantia, the Columbia arms dependency, and the Gulf security architecture keep Mirage firmly in the Western orbit for defense. Military capability is modest but the air defense systems have been tested in combat against Persian barrages. Authoritarian prosperity keeps stability high and support strong — but if the skyline keeps getting hit and capital flees, the social contract frays. The country that wanted no enemies now has one across the Gulf with nothing to lose.
$$ WHERE id = 'mirage' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- PHRYGIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Phrygia is the ultimate swing state — a Western Treaty member that buys Sarmatia air defense systems, a BRICS+ observer that hosts the alliance summit, a mediator in the Ruthenia war that profits from both sides, and a country whose president has turned strategic ambiguity into a personal art form. President Vizier has governed for over two decades, concentrating power in a presidential system that makes foreign policy intensely personal. The result: a country everyone needs for something and nobody trusts for anything. Columbia needs the Bosphorus and the alliance's southern flank. Sarmatia needs energy transit routes and sanctions workarounds. Cathay needs an alliance insider. The Ereb Union needs migration management. Gulf states need a power broker.

The Bosphorus Strait is Phrygia's trump card. The only passage between the Black Sea and the Mediterranean, controlled under international convention with legal authority to restrict warship transit during wartime. This gives Phrygia the ability to block Sarmatia naval access (or allow it), leverage over the Ruthenia conflict, and bargaining power with every maritime nation that needs Black Sea access. The strait control card can be played each round as a diplomatic lever.

The economy is the constraint that drives the dealing. Inflation is among the highest in the simulation for a non-collapsed state, having come down from catastrophic peaks but still devastating in real purchasing power. Unorthodox economic policies created the crisis; the belated return to orthodoxy is producing painful correction. Gulf investment and Sarmatia energy deals keep the economy afloat. Foreign policy flexibility is partly a function of economic desperation — Phrygia cannot afford to alienate any source of capital. The trade deficit and debt burden leave almost no fiscal cushion.

Militarily, Phrygia fields one of the largest Western Treaty forces by personnel. The domestic defense industry is a genuine success — combat drones are an export hit, and warship production is competitive. Phrygia supplied drones to Ruthenia while buying advanced air defense systems from Sarmatia — the purchase that cost access to Columbia's next-generation fighter program. The Syria dimension adds depth: following the regime change, Phrygia has secured major energy and infrastructure contracts, positioning as a hub connecting Caspian gas, Gulf LNG, and European markets. The Persia war complicates everything — missiles were shot down over Phrygian territory, the shared border means refugee flows and energy disruption, and involuntary involvement in a conflict serving no Phrygian interest. Vizier IS the system — a hybrid regime under permanent economic stress with no succession mechanism.
$$ WHERE id = 'phrygia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- SOLARIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Solaria is the world's energy pricing superpower under direct military threat for the first time in a generation. Crown Prince Wellspring — young, ambitious, transformational, and ruthless — has spent a decade remaking the kingdom: social liberalization, tourism megaprojects, and a massive diversification program built on the bet that oil wealth now can build a post-oil economy before the wells run dry. That bet is under unprecedented stress.

When Columbia and Levantia struck Persia, the retaliatory missile barrage hit Solaria's oil infrastructure directly. One of the world's largest refineries went into partial shutdown. For the first time in history, Persia attacked all six Gulf states simultaneously. Solaria raised military readiness to maximum. The kingdom that cultivated "no enemies" diplomacy is now hosting the air war against its neighbor across the Gulf, with Columbia troops on its soil.

Every country's economic health depends on oil prices, and Solaria controls the tap. As the Cartel's de facto leader with the majority of the world's spare production capacity, Solaria's production decisions reshape the global economy. The production dial is the single most consequential economic lever any solo country possesses. A healthy trade surplus, an enormous starting treasury backed by one of the world's largest sovereign wealth funds, and growing GDP make Solaria one of the wealthiest players in the simulation.

The hedging strategy remains intact despite the war. BRICS+ membership signals multipolarity. Cathay is a major crude customer and provides technology Columbia will not share. Sarmatia is an OPEC+ partner. Bharata is a growing energy customer. Wellspring has stated publicly that Solaria will develop nuclear weapons if Persia acquires them — the nuclear proliferation question looms over every outcome of the Persia war. The military is professional but combat-untested, equipped with Columbia systems whose air defense batteries were tested against Persian missile barrages with mixed results. Wellspring has concentrated power more completely than any ruler in modern history, eliminating rival princes. This means fast decisions but no institutional brake if he miscalculates. If oil facilities are destroyed and the economy contracts, the social contract — prosperity in exchange for political quiescence — frays at its foundation.
$$ WHERE id = 'solaria' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- YAMATO
-- ============================================================================
UPDATE countries SET country_brief = $$
Yamato is quietly undergoing its most significant military transformation since 1945 — a Pacific democracy with the fourth-largest economy, among the world's largest foreign exchange reserves, and a defense buildup that has achieved its spending target ahead of schedule under Cathay anxiety and Columbia pressure. The record defense budget funds standoff missiles, next-generation fighter jets jointly developed with Albion and Ponte, unmanned systems, and integrated missile defense. Yamato is building the capacity to strike Cathay's coastal military infrastructure — a capability that was politically unthinkable a decade ago.

The nuclear dimension is latent but real. Yamato possesses the technical infrastructure — advanced reactors, fissile material stockpiles, missile technology, and scientific expertise — to develop nuclear weapons within a few years. The prime minister has publicly discussed relaxing the non-nuclear principles. This "latent capability" is a strategic signal that shapes every calculation in the Pacific. Whether Yamato would go nuclear — and at what cost to the Columbia alliance — is one of the simulation's most consequential questions.

Columbia's main Pacific base sits on Yamato's territory — the hub that makes Formosa deterrence possible. Yamato hosts tens of thousands of Columbia personnel. The alliance is the cornerstone of Pacific security, but Columbia's transactional approach under Dealer raises the question every strategist fears: what if Columbia does not come? Yamato is remilitarizing because it no longer fully trusts the protection. Formosa semiconductor dependency is the highest in the simulation outside Formosa itself — if those fabs are destroyed, Yamato's electronics industry collapses.

The structural weakness is demographic. Births have fallen for years in a row. The population is aging and shrinking. The economy has stagnated for decades despite massive accumulated wealth. Sovereign debt relative to output is the highest in the world, though almost entirely domestically held and denominated in the national currency. Social spending for the aging population grows every year and is politically untouchable. The military transformation represents quality over quantity — a highly capable Pacific fleet, modern air forces, and advanced missile defense. Stability is the highest in the simulation, reflecting mature democratic institutions and social cohesion. But deep pacifist instincts — a gap between intellectual acceptance of rearmament and emotional readiness for conflict — could close overnight if Cathay moves on Formosa. Until then, the transformation proceeds incrementally, anxiously, and with growing independence.
$$ WHERE id = 'yamato' AND sim_run_id = '00000000-0000-0000-0000-000000000001';
