-- Country Briefs for TTT Simulation
-- Generated from SEED design documents: A_SCENARIO, B_ACTORS, C_MECHANICS
-- All names are fictional. All data references game values.
-- sim_run_id = '00000000-0000-0000-0000-000000000001' (template/reference run)

-- ============================================================================
-- COLUMBIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Columbia is the world's preeminent power — a federal democracy with a GDP of 280 coins, the largest military on earth (67 units across four continents), and a nuclear arsenal rivaled only by Sarmatia. It leads the Western Treaty alliance, holds a permanent veto on the Council, and chairs the Seven. Its currency underpins global trade. Its semiconductor supply chain runs through Formosa, where a single company fabricates 65% of the advanced chips Columbia's economy and military depend on. For thirty years, no nation could challenge this dominance. That era is ending.

At simulation start, Columbia is fighting a war in Persia (Operation Epic Fury), sustaining a proxy conflict in Ruthenia, deterring Cathay in the Pacific, and waging a trade war whose legal foundations have been struck down by its own courts. President Dealer — age 80, approval at 38%, term-limited — launched the Persia campaign without legislative authorization. Two carrier strike groups and 10 military units are locked in the Middle East theater. Gas prices are surging. The first-ever trillion-coin defense budget strains a fiscal position already hemorrhaging 12 coins per round in trade deficit, with debt service at 5 coins and 30% of GDP locked into untouchable social spending. There is no strategic reserve. Any new crisis — a Cathay move on Formosa, a Choson provocation, a Sarmatia escalation — would require pulling forces from an existing commitment.

The succession race defines Columbia's internal politics. Vice President Volt and Secretary of State Anchor are already positioning for the presidential election at Round 5. Volt represents isolationist conservatism; Anchor represents hawkish interventionism with the Caribe regime change as his personal trophy. Their competing agendas mean Dealer's orders risk being slow-walked by subordinates calculating their own futures. Tribune leads the congressional opposition with the power to flip the legislature at Round 2 mid-terms. Challenger campaigns from outside, offering every foreign leader an alternative future. Shadow controls what intelligence Dealer sees. Shield manages an overstretched military with a philosophy that concerns career officers.

Every other country's strategy depends on what Columbia does. But Columbia itself cannot agree on what to do — because its president is chasing legacy, its successors are chasing power, its opposition is chasing the presidency, and the world will not wait for any of them to decide. Columbia's overstretch is not a temporary condition. It is the structural reality of a hegemon whose commitments have outgrown its capacity and political will — the classic precondition of the Thucydides Trap.
$$ WHERE id = 'columbia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- CATHAY
-- ============================================================================
UPDATE countries SET country_brief = $$
Cathay is the rising pole of the Thucydides Trap — the world's second-largest economy (190 coins GDP), its largest manufacturer, its fastest-growing nuclear power, and the only nation with the structural trajectory to displace Columbia as global hegemon. Chairman Helmsman holds more personal power than any leader in Cathay's modern history: he has abolished term limits, purged over 100 senior military officers, and concentrated party, state, and military authority under singular control. There is no successor. There is no alternative center of power. There is only the Chairman and his vision of national rejuvenation — a vision that requires, before it can be declared complete, the resolution of the Formosa question.

The military paradox defines Cathay's position. The People's Liberation Army fields the world's largest navy by hull count, a nuclear arsenal expanding from 600 warheads toward 1,500, and a missile force that can hold Columbia's Pacific bases at risk. Naval production outpaces all Western navies combined. But five of seven Central Military Commission members have been purged. Marshal Rampart — the replacement — has no operational command experience. For the first two rounds, any complex military operation carries a 20% chance of implementation failure. The military is simultaneously more powerful and less competent than it has ever been.

Cathay's economy is a war machine running on export adrenaline while its domestic engine sputters. A record 12-coin trade surplus masks a property sector that has lost half its value, deflation persisting for a third year, youth unemployment near 18%, and a population declining for the fourth consecutive year. The technology race adds urgency: domestic AI chip production is advancing (SMIC at 7nm, DeepSeek V4 competitive with frontier models), but Cathay remains a decade behind in advanced lithography. Rare earth dominance — 90% of global refining — is the strongest leverage card. If Columbia reaches AI Level 4 first, the technological advantage may become permanent.

Behind the unified facade, five forces pull in different directions. Helmsman demands Formosa. Rampart cannot guarantee military success. Premier Abacus sees economic data showing confrontation leads to catastrophe. Circuit knows war would destroy the supply chains his tech empire depends on. Elder Sage waits — knowing that if the Chairman overreaches, the party's survival instinct will produce a correction. The disagreements are never public. They manifest as biased briefings, slow-walked orders, and selective information. The outside world can only guess. The window for action on Formosa may be opening — or it may already be closing. That uncertainty is the Trap.
$$ WHERE id = 'cathay' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- GALLIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Gallia is Europe's most ambitious and most domestically constrained power — a nuclear-armed democracy with a GDP of 34 coins, a permanent Council veto, the continent's only independent carrier strike group, and a president whose approval rating sits between 11% and 16%. President Lumiere governs without a parliamentary majority, his domestic agenda paralyzed, but the constitutional prerogatives of the presidency give him near-unchallenged authority over defense and foreign affairs — and he is using every drop of it.

The forward deterrence speech represents the most significant shift in Gallia's nuclear doctrine in decades. Gallia will increase its warhead stockpile beyond the long-maintained ceiling of approximately 300 for the first time since 1992. The new doctrine extends a consultative nuclear umbrella to eight allied nations, including Teutonia, Freeland, and Albion. But Gallia retains sole decision-making authority — the button remains in its capital. This nuclear gambit is simultaneously a bid for European leadership, a hedge against Columbia's transactional unreliability, and a personal legacy project. It places Gallia at the center of every European defense conversation — but at the cost of deepening the Atlanticist-autonomist split that divides the continent.

Gallia deployed an unprecedented naval force to the Gulf independently of Columbia's Persia campaign — monitoring, not fighting, but demonstrating capacity for unilateral action that no other European power except Albion possesses. With 16 military units, a domestic defense industry (Dassault, Naval Group, Thales), and global bases from the Pacific to the Horn, Gallia can project power where others can only deliberate. The constraint is fiscal: 45% tax rate, 112% debt-to-GDP, and a social spending floor of 35% that is politically untouchable.

The player who runs Lumiere holds the only independent nuclear deterrent in the Ereb Union, the only Council veto among EU members, the most deployable military on the continent, and the most ambitious vision for European strategic autonomy. The tension with Freeland (which sees autonomy as weakening the Western Treaty) and with Teutonia (which prioritizes trade preservation over defense ambition) is the fault line that defines European politics. Gallia's grandest ambitions rest on the narrowest political foundations — a president with everything except domestic support.
$$ WHERE id = 'gallia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- TEUTONIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Teutonia is Europe's indispensable and most conflicted power — the continent's largest economy (45 coins GDP), its industrial engine, and the country whose every decision on trade, sanctions, and defense spending determines whether Europe confronts or accommodates the world's rising authoritarian powers. Chancellor Forge governs with a new mandate after snap elections, inheriting an economy that has stagnated since 2017 and endured three consecutive years of recession. Manufacturing jobs are disappearing at a rate of 10,000 per month. The industrial base that made Teutonia Europe's powerhouse is under assault from Cathay's competition, Columbia's tariffs, and energy costs that never returned to pre-2022 levels.

Forge's response is the most ambitious rearmament since 1945 — a 100-billion-coin infrastructure and defense fund approved via constitutional amendment. Defense spending has crossed 100 billion, targeting 3.5% of GDP by 2029, but starting from a chronically low base. The Bundeswehr has been underfunded for decades; procurement is slow, bureaucratic, and plagued by delays. Six ground units, zero strategic missiles, zero nuclear weapons. Teutonia hosts Columbia's main European base at Ramstein — leverage and dependency simultaneously. Columbia demands 5% defense spending, restricted Cathay trade, and acceptance of the Thule pressure. These demands are contradictory and economically impossible to satisfy simultaneously.

The Cathay trade dependency is the constraint on everything. Teutonia's automotive and chemical industries (VW, BMW, BASF) are deeply intertwined with Cathay's market and supply chains. Cathay uses this dependency to prevent Teutonia from fully joining Columbia's technology restriction regime. Columbia demands Teutonia restrict trade; Cathay warns that restriction means industrial collapse. The 45% Formosa semiconductor dependency adds technological vulnerability on top of market exposure. "De-risking" is official policy — but de-risking is not decoupling, and every industrialist in Teutonia knows the difference.

Teutonia holds the EU checkbook and the deciding vote on whether Europe confronts or accommodates Cathay. Every economic decision in the Ereb Union runs through this country. But economic power comes with economic vulnerability — and that vulnerability is the constraint on every strategic choice Forge faces.
$$ WHERE id = 'teutonia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- PONTE
-- ============================================================================
UPDATE countries SET country_brief = $$
Ponte is Europe's most consequential swing vote and its most financially vulnerable major power — a democracy with 22 coins GDP, 137.9% debt-to-GDP ratio, and 8 coins per round consumed by debt service alone. That fiscal reality means virtually no discretionary spending exists. Every policy choice is a fiscal choice, and whoever offers financial relief — Ereb Union recovery funds, Cathay investment, sanctions waivers — has leverage over Ponte's alignment. The third-largest EU economy and a G7 member, Ponte punches above its economic weight through sheer institutional position: it can veto any EU decision requiring unanimity, from sanctions on Sarmatia to Ruthenia's accession to trade restrictions on Cathay.

The governing coalition is fractious. Two of three coalition parties publicly question continued support for Ruthenia and sanctions on Sarmatia. One coalition leader has been accused of receiving Sarmatia funds and openly criticizes sanctions as harmful to domestic businesses. The March 2026 referendum defeat — 54% to 46% against the government's flagship judicial reform — weakened the prime minister's domestic mandate and emboldened coalition dissent. Ponte's chronic political instability (68 governments since 1946) means collapse is always a possibility, and a new government might be more Sarmatia-friendly, more Cathay-curious, and more willing to use the EU veto as a weapon.

Ponte is Columbia's favorite European partner — the only EU leader invited to the Dealer's inauguration, bonded by shared ideology and personal chemistry. This relationship makes Ponte the bridge between Columbia and the Ereb Union, trusted where others are despised. But it also makes Ponte the potential crack in European unity. When Ponte calls for Europe to "reach out to Sarmatia over peace," it carries weight that smaller dissenters never could, because Ponte is a founding EU member, a G7 economy, and a Western Treaty ally with a real military — 4 ground units, 2 naval, 2 tactical air, including a carrier.

Ponte's defection from the sanctions consensus would not just embarrass the EU. It would shatter it. That is why every diplomatic deal in Europe must account for whether Ponte will sign — and what Ponte wants in return.
$$ WHERE id = 'ponte' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- FREELAND
-- ============================================================================
UPDATE countries SET country_brief = $$
Freeland is the Western Treaty's most committed conventional military power and Europe's security conscience — a frontline democracy with 9 coins GDP, 4.8% of GDP allocated to defense (the highest ratio in the alliance), and a 200-billion-zloty military budget that shames every partner on the continent. This is not posturing. Freeland borders Sarmatia's exclave and the Ruthenia conflict zone. Eighty percent of all military aid to Ruthenia has transited Freeland territory through the logistics hub in its eastern city. For this country, the war next door is not an abstraction — it is the confirmation of everything Freeland warned about for decades while others built gas pipelines to Sarmatia.

The military buildup is real and accelerating: 5 ground units (with K2 tanks from joint production ventures), 2 tactical air units (F-35 procurement underway), 1 naval unit in the Baltic, and 1 air defense battery. Production capacity is expanding through defense industry partnerships. Columbia forward-deployed troops are hosted on Freeland soil. The goal of 5% GDP defense spending — years ahead of the alliance's 2035 target — is being achieved on the fastest-growing economy in Europe (3.7% GDP growth).

Freeland's strategic dilemma: it wants maximum Western Treaty commitment AND maximum Ereb Union solidarity, but these sometimes conflict. When Gallia pushes strategic autonomy, Freeland hears "weakening the alliance we depend on for survival." When Teutonia prioritizes Cathay trade, Freeland sees dangerous appeasement. When Columbia demands 5% spending, Freeland already exceeds it — giving moral authority to shame those who do not. The relationship with Ruthenia is the deepest bond: neighbor, weapons transit corridor, refugee host, and existential solidarity forged by shared understanding of the Sarmatia threat.

Domestically, Sentinel governs with a stable pro-EU coalition but faces an opposition president who can veto legislation and EU defense loans, creating friction on specific policies without undermining the broad security consensus. On defense and Ruthenia, there is near-unanimity across the political spectrum. Freeland speaks with the authority of a nation that lives next to the threat everyone else debates abstractly — the smallest economy among major European powers, but the largest military commitment.
$$ WHERE id = 'freeland' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- ALBION
-- ============================================================================
UPDATE countries SET country_brief = $$
Albion is Europe's second-largest military power, a nuclear state, a permanent Council member with veto power, and a core member of the Five Eyes intelligence alliance — all wielded from outside the Ereb Union. With 33 coins GDP, the strongest navy in Europe (4 naval units including 2 aircraft carriers), 2 strategic missile units (Trident submarines on continuous patrol with approximately 225 warheads), and global bases from Cyprus to the Falklands, Albion possesses capabilities no other European nation can match. The structural problem is unique: Albion participates in Western Treaty military coordination but cannot vote on any EU decision affecting sanctions, trade, enlargement, or defense spending. Influence without a seat at the table where economic decisions happen.

Five Eyes is the unique trading chip. Columbia shares intelligence with Albion that it does not share with EU allies through alliance channels. This means Albion can selectively share intelligence with European partners — Gallia, Teutonia, Freeland — to buy influence and cooperation. The intelligence asymmetry is real and consequential: Albion knows things about Sarmatia's military posture, Cathay's intentions, and Columbia's internal deliberations that other European nations can only access through Albion's willingness to share.

Prime Minister Mariner has seized diplomatic initiative on Ruthenia — hosting virtual meetings of Western leaders, initiating a "coalition of the willing" for peace deal implementation, and offering Albion troops as part of a ceasefire monitoring force. This activism is rebuilding European partnerships damaged by the exit from the EU and demonstrating post-departure relevance through military capability and diplomatic leadership. The Strategic Defence Review accepted recommendations for nuclear modernization (including a second delivery system beyond the submarine deterrent), a reserve corps of two army divisions, and enhanced maritime contribution to the North Atlantic. Defense spending targets 2.5% of GDP by 2027 and 3% by end of parliament.

Albion's constraint is fiscal: 100% debt-to-GDP, 3 coins per round in debt service, 30% social spending baseline, and persistent trade deficits. The nuclear deterrent alone absorbs 25% of the defense budget. The economy is services-dominated with the financial center as the crown jewel, but post-departure trade friction with the EU persists. Mariner must project global ambition on a national budget that is already stretched — the eternal Albion challenge of a medium-sized economy with great-power aspirations.
$$ WHERE id = 'albion' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- SARMATIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Sarmatia is a nuclear superpower fighting a grinding land war in eastern Ruthenia, under the heaviest Western sanctions regime in history, led by a 73-year-old president who has concentrated more personal power than any leader since the Soviet era — and who has no successor. The war, now in its fifth year, defines everything. Launched as a three-day special operation to decapitate a neighboring government, it became the largest conventional war in Europe since 1945. Sarmatia occupies approximately 20% of Ruthenia's territory across four annexed oblasts — a claim it cannot fully enforce militarily. Thirteen of eighteen ground units are committed to the theater. Casualties may exceed one million. North Korean troops fight alongside Sarmatian forces.

The economy has proven more resilient than Western analysts predicted — and more fragile than the leadership admits. GDP of 20 coins, growth collapsed to 1%, defense spending consuming 40% of the federal budget. Oil revenues — the lifeblood — are declining as sanctions bite and Cathay demands ever-deeper discounts. The Central Bank rate sits at 15%, inflation is being muscled down from double digits. The National Wealth Fund is depleted. Sanctions have disconnected major banks from the global financial system, restricted technology imports, and frozen approximately 300 billion in foreign reserves. The economy works for now. It will not work indefinitely.

Pathfinder's control is absolute in formal terms but depends on information filtered by subordinates. Ironhand controls the military and co-authorizes nuclear launch — the one thing Pathfinder cannot do without him. Compass manages an economy whose real numbers (stagnation, depleting reserves, collapsing regional budgets) are worse than what reaches the president, and holds 3 personal coins frozen abroad by sanctions — a direct financial incentive for peace that may diverge from Pathfinder's territorial ambitions. The partnership with Cathay provides economic survival but at the cost of becoming the junior partner in an increasingly asymmetric relationship. The nuclear arsenal — the world's largest at approximately 5,500 warheads, now unconstrained by any treaty — remains the ultimate guarantor of sovereignty.

Sarmatia must decide whether to consolidate, escalate, or negotiate. Pathfinder's legacy demands something he can call victory. The general wants either a real military result or an honest admission that one is impossible. The oligarch wants the war over and sanctions lifted. The war economy drain (2 extra coins per round) and cumulative war tiredness (currently 4, rising each round) create a structural clock: time is not on Sarmatia's side, even if the front line holds.
$$ WHERE id = 'sarmatia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- RUTHENIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Ruthenia is the human cost of the Thucydides Trap made visible — a wartime democracy of 2.2 coins GDP fighting for survival against a nuclear superpower, sustained by Western aid that could be cut at any moment, and governed by three leaders who represent three genuinely different responses to an impossible situation. The war, now in its fifth year, has destroyed 14% of all housing, pushed public debt beyond 123% of GDP, and created reconstruction needs of 588 billion over the next decade — three times the country's annual output. The economy functions because the West keeps it alive: European aid rose 67% as Columbia's aid collapsed by 99%.

Seven of ten ground units hold the front line against thirteen Sarmatian ground units — a 1:1.85 disadvantage partially offset by defensive positions, Western weapons (F-16s, HIMARS, Storm Shadow), and higher motivation. The navy was destroyed in 2022 but innovative drone warfare forced Sarmatia's Black Sea Fleet from its base. Ruthenia has zero strategic missiles — it surrendered its nuclear arsenal under the Budapest Memorandum in exchange for security guarantees that proved worthless. That foundational betrayal shapes every negotiation: promises are paper, only capabilities are real. Air defense is the most critical scarce resource — a single unit of Western-supplied Patriot and NASAMS systems must protect the capital and critical infrastructure from relentless missile and drone barrages.

The three-way political competition defines Ruthenia's direction. President Beacon — wartime hero, approval falling to 52%, first-round polling at 22.6% — holds executive power under martial law but faces eroding legitimacy after a corruption scandal. General Bulwark commands the army's loyalty and would win a runoff 64-36 — his restraint in refusing to seize power is both principled and strategic. Former president Broker has neither military credibility nor executive power but has European connections and the argument that negotiated peace, not endless war, saves the country. The election (Round 3 or 4) will be triggered by external pressure, stability collapse, or candidate initiative.

Columbia's 28-point peace plan would cede Crimea, Donetsk, and Luhansk to Sarmatia and constitutionally bar Ruthenia from the Western Treaty. Eighty-two percent of citizens find territorial cession unacceptable. But 63% say they are ready to continue fighting — a number that was 80% in 2022 and is falling. EU membership — the one guarantee Ruthenia trusts — is blocked by Ponte. The gap between what the population will accept and what the world is offering is the political crisis. Aid dependency (2 coins per round from the Western coalition) means economic survival is not guaranteed — if aid drops below 1 coin, stability collapses immediately.
$$ WHERE id = 'ruthenia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- PERSIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Persia is a hybrid regime under bombardment — at war simultaneously with Columbia and Levantia since February 28, 2026, when Operation Epic Fury killed the previous Supreme Leader and devastated the country's military infrastructure. The new Supreme Leader, installed through a rushed selection orchestrated by the IRGC commander, lacks religious authority and commands nothing independently. The IRGC commands everything: the military campaign, the Gulf Gate blockade, the proxy remnants, and a veto over diplomatic decisions. The reformist president attempted to apologize to Gulf states for retaliatory strikes — the IRGC shut him down within hours. Three forces compete behind a theocratic facade: the fundamentalist who would rather burn than bend, the general who controls everything and calculates in power and profit, and the reformist who speaks for 70 million people wanting normal life but has no guns.

Persia's strategic position rests on a single asset: the Gulf Gate blockade. Within hours of the strikes, the IRGC closed the strait using a layered ground-based area denial system — coastal anti-ship missile batteries hidden in mountains, island fortifications, 5,000-6,000 mines in shipping lanes, swarm boats, and submarine operations. This is not a naval blockade that can be sunk from the air. Tanker traffic dropped 70%. Oil surged past $120 per barrel. The global economy bleeds while the bombs fall. But the blockade is a wasting asset: each round costs Persia 0.5 coins in lost oil revenue while maintaining it, and sustainability is estimated at 4-5 rounds maximum. The question is whether to negotiate from strength now or hold until the regime breaks.

The economy is in catastrophic contraction. GDP of 5 coins, inflation between 45-60%, the rial collapsed to over 1,100,000 against the dollar. Revenue of 0.9 coins per round against maintenance costs of 4.25 coins plus 1.5 coins war drain — the deficit is existential. The IRGC's parallel economic empire (one-third of the economy, over 100 companies, $12 billion annual revenue) funds military operations independently of the state budget, giving Anvil both the means and the financial incentive for selective deals. The nuclear program sits at 60% progress toward Level 1 — if achieved, it fundamentally changes the strategic calculus. Air defense is a single unit that must protect either nuclear facilities or the leadership, but not both simultaneously.

Columbia cannot break the Gulf Gate blockade without a ground invasion that would cost thousands of lives. Persia cannot survive indefinitely under bombardment. Both sides are stuck — and the resolution depends on which internal voice prevails.
$$ WHERE id = 'persia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- BHARATA
-- ============================================================================
UPDATE countries SET country_brief = $$
Bharata is the genuine third pole of global politics — a 42-coin GDP democracy with the world's largest population, the fastest growth rate among major economies (6.5%), and a foreign policy built on strategic ambiguity that makes it indispensable to every side and fully committed to none. Columbia desperately needs Bharata in the sanctions coalition against Sarmatia and as a counterweight to Cathay. Cathay needs Bharata to legitimize BRICS+ alternatives and stay out of Columbia's orbit. Sarmatia needs Bharata to keep buying weapons and discounted oil. Everyone comes to Bharata. Bharata says "yes, but..." to everyone.

Bharata hosts the 2026 League (BRICS+) summit — the institutional platform for non-Western alternatives to dollar hegemony, Western sanctions architecture, and Columbia-led global governance. A currency union vote is expected by Round 3. Bharata holds a rotating Council seat, aspires to permanent membership, and uses every forum to demonstrate global stature without binding commitment. The February 2026 trade deal with Columbia cut tariffs to 18% while maintaining defense cooperation — Quad partner, deepening military ties — but Bharata simultaneously buys Sarmatian weapons (S-400 air defense), imports discounted Sarmatian and Persian oil, and refuses to join any sanctions regime. The non-alignment dividend is real: Bharata faces no technology export restrictions and benefits from both Columbia and Cathay tech ecosystems.

The military is the third-largest ground force in the simulation (12 units), with a growing blue-water navy, nuclear weapons (Level 1, 170 warheads), and diversified procurement from both Western and Sarmatian suppliers. The primary security concern is the Cathay border — the Ladakh dispute creates permanent friction with the regional rival, and both powers compete for influence across South Asia, the Indian Ocean, and Africa. If Cathay moves on Formosa or escalates at Ladakh, non-alignment collapses overnight. Bharata becomes Columbia's ally by necessity, not choice — and loses everything built with the other side.

The economy is consumption-driven with strong structural momentum from demographics — the opposite of Cathay's aging crisis. But oil import dependency (85% of needs) means the Persia war price spike directly hurts. The 5% inflation rate is manageable but food price volatility is a constant political risk. Hindu-nationalist governance creates periodic communal tension that complicates relationships with Muslim-majority countries. The 200-million-strong Muslim minority means any overt alignment with Levantia against Persia carries domestic political cost. Bharata's leverage is its refusal to commit — the question is how long ambiguity remains a strategy rather than a luxury of peacetime.
$$ WHERE id = 'bharata' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- CARIBE
-- ============================================================================
UPDATE countries SET country_brief = $$
Caribe is the Western hemisphere's crisis state — a composite of Caribbean socialist regimes in existential collapse after Columbia's most dramatic regional intervention in decades. Operation Absolute Resolve (January 2026) seized one nation's president in a surprise military raid, flew him to trial on narco-terrorism charges, and triggered the imposition of a comprehensive energy blockade on the other. Executive Order 14380 declared a national emergency, blocked oil tankers, and threatened tariff retaliation against any country supplying fuel. The first effective naval blockade since the 1962 missile crisis has cut off an island that produces barely 40% of the fuel it needs.

The consequences have been devastating. In March 2026, a nationwide blackout disconnected the entire electrical system, leaving 11 million people without power. The leadership admitted no foreign oil had been received for three months. GDP of 2 coins is contracting at -1% annually. Inflation runs at 60%. The treasury holds 1 coin. Debt burden relative to GDP is the highest in the simulation at 5 coins per round against a revenue base that can barely service it. The economy is functionally collapsed — surviving on Cathay's $80 million in financial assistance and 60,000 tons of rice, and Sarmatia's pledged oil shipments that Columbia's naval interdiction makes uncertain to deliver.

Military capability is negligible: 3 ground units of demoralized and poorly equipped forces, 1 coastal patrol vessel, 1 unit of antiquated tactical air. No strategic weapons, no air defense, no production capacity for naval or air units. Stability sits at 3 — severe crisis, one more shock from unrest. Troop morale is at -1. The regime survives through repression and emergency measures, not popular support.

But Caribe holds one card that no amount of military weakness can negate: geography. Ninety miles from Columbia's mainland, the ability to invite Sarmatia or Cathay military assets — missiles, intelligence facilities, naval visits — onto Caribbean territory automatically creates a domestic political crisis in Columbia. Sarmatia already operates signals intelligence facilities monitoring Columbia from this location. Cathay has embedded telecom infrastructure. The Monroe Doctrine trigger is the cheapest, most effective provocation in the simulation. Columbia cannot tolerate foreign great-power military presence in its backyard. That vulnerability is Caribe's leverage — the desperate gambit of a failing state that has nothing to lose.
$$ WHERE id = 'caribe' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- CHOSON
-- ============================================================================
UPDATE countries SET country_brief = $$
Choson is the world's most dangerous minor power — a nuclear-armed totalitarian state with 0.3 coins GDP, the smallest economy in the simulation by an order of magnitude, and a talent for manufacturing crises at the worst possible moment for everyone else. Supreme Leader Pyro, in his early forties, has cemented power after a decade of purges and nuclear tests. In March 2026, he vowed to "irreversibly cement" Choson's nuclear status, ordering accelerated missile production and expanded ICBM complexes. The nuclear arsenal is estimated at 40-60 warheads with an expanding delivery capability — land-based ICBMs that can theoretically reach Columbia's continental territory, submarine-launched missiles (development accelerated by Sarmatian technology transfers), and tactical nuclear weapons for battlefield use.

The Sarmatia deployment is the defining development. Over 15,000 troops have been sent to fight in the Ruthenia war since late 2024 — the first overseas combat deployment by a Choson force since 1953. Casualties exceed 6,000 — half the original force. A third deployment wave of 6,000 is preparing. In exchange: submarine propulsion systems, possibly nuclear reactor components, and military technology transfers that are accelerating Choson's nuclear modernization faster than sanctions could prevent. The blood-for-technology trade is the most consequential bilateral relationship Choson has.

Cathay provides approximately 90% of Choson's trade and energy — the economic lifeline. But Cathay is embarrassed by Choson's provocations and fears nuclear proliferation destabilizing the region. Cathay tolerates Choson because the alternative — regime collapse and Columbia troops on Cathay's border — is worse. Choson exploits this calculation ruthlessly. The March 2026 missile barrage — 10 simultaneous launches — demonstrated provocative capability at unprecedented scale. Seoul, with 25 million people, sits 35 miles from the DMZ under thousands of artillery pieces. The threat is not nuclear — it is conventional. Choson can devastate the Hanguk capital in hours without crossing the nuclear threshold.

Choson's power is crisis on demand. A nuclear test, an ICBM launch over Yamato, an artillery barrage near the DMZ — any of these can be triggered at any time, forcing Columbia, Hanguk, Yamato, and Cathay to divert attention and resources from whatever they were doing. During the Persia war, when Columbia is maximally overstretched, this capability is at its most dangerous. The regime spends 25-30% of GDP on the military. The population endures conditions that would cause revolution anywhere else, but the totalitarian surveillance apparatus prevents organized dissent. There is no succession mechanism. If the leader is incapacitated, the system has no plan.
$$ WHERE id = 'choson' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- FORMOSA
-- ============================================================================
UPDATE countries SET country_brief = $$
Formosa is the most dangerous tripwire in the world — a functionally independent democracy of 24 million people that fabricates the majority of the planet's advanced semiconductors, claimed as sovereign territory by the simulation's rising great power, and defended by the declining hegemon under a policy of deliberate ambiguity. TSMC, Formosa's crown jewel, produces nearly one-third of all global computing power and the vast majority of cutting-edge chips below 7nm. Every AI model trained, every advanced weapons system built, every smartphone sold depends on facilities concentrated on this single island. The "silicon shield" is Formosa's greatest strategic asset — the world cannot afford to let these fabs be destroyed or captured.

But the shield is eroding. Columbia's CHIPS Act fabs, Yamato's Rapidus project, and Cathay's own semiconductor push all reduce the concentration that makes Formosa indispensable. Every fab built abroad makes the island marginally more expendable. At simulation start, Columbia's Formosa semiconductor dependency stands at 0.65 — still critically high, but falling. Cathay's is 0.25 and declining faster. The window in which Formosa's economic value protects it from military action is closing.

Cathay's military pressure is relentless. Record air incursions, major exercises, and the largest military buildup ever pointed at a single target. A selective quarantine could cripple Formosa's semiconductor supply chain within weeks — the island depends on imported natural gas, chemicals, and raw materials. Full invasion remains the nightmare scenario, but blockade or quarantine offers Cathay a gray-zone option harder for Columbia to counter with military force. Formosa's own military — 4 ground units, 2 naval, 3 tactical air, 2 air defense — is configured for asymmetric "porcupine" defense: delay the invasion fleet, make the island indigestible, and hold until Columbia arrives. Whether Columbia arrives is the question nobody can answer.

Internal gridlock compounds the vulnerability. The pro-sovereignty president proposed a landmark $40 billion special defense budget. The opposition-controlled legislature — sympathetic to cross-strait engagement — slashed it by 70% and launched impeachment proceedings. Formosa cannot agree on how seriously to take its own defense. The economy (8 coins GDP, 3% growth, massive trade surplus of 4 coins) is healthy but entirely dependent on continued semiconductor demand and continued peace. A 55% political support level masks a genuine societal split between those who would resist and those who would accommodate Cathay. Columbia watches with alarm as its protectorate fails to implement the defense strategy it considers essential.
$$ WHERE id = 'formosa' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- HANGUK
-- ============================================================================
UPDATE countries SET country_brief = $$
Hanguk is a technology superpower caught between the two poles of the Thucydides Trap, with a nuclear-armed adversary 35 miles from its capital and a new president trying to navigate between alliance loyalty and economic survival. The December 2024 martial law crisis — a six-hour constitutional emergency that triggered presidential impeachment and conviction — traumatized the nation and damaged institutional trust in the presidency itself. The snap election brought a liberal leader to power on a centrist platform of stability and diplomatic recalibration. President Vanguard represents a sharp pivot: warming to Cathay (state visit with Samsung and SK Group chairmen), reaffirming the one-Cathay stance on Formosa, while maintaining the trilateral security architecture with Columbia and Yamato.

The semiconductor industry is Hanguk's strategic crown jewel and vulnerability simultaneously. Samsung and SK Hynix together account for roughly 60% of global memory chip production. But nearly half of the rare earth minerals for semiconductor manufacturing come from Cathay. Columbia's chip export controls pressure Hanguk to restrict sales to Cathay; Cathay's firms are launching alternative AI chips in Hanguk as replacements for Columbia products. Hanguk is the battleground of the tech war — squeezed between the supplier and the customer, with 18 coins GDP and a trade surplus of 3 coins that depends on both relationships surviving intact.

The Choson threat is escalating in real time. The March 2026 missile barrage of 10 simultaneous launches demonstrated unprecedented provocative capability. Choson troops are gaining combat experience and Sarmatian military technology in the Ruthenia war. The DMZ remains the most militarized border on earth. Hanguk's military — 5 ground units, 2 naval, 3 tactical air, 2 air defense — is entirely oriented toward this threat. Columbia's base (1 ground, 1 tactical air, 28,500 troops) serves as an automatic tripwire. The nuclear debate simmers beneath the surface: public polling consistently shows majority support for developing indigenous nuclear weapons if Columbia's extended deterrence proves unreliable.

Vanguard governs with a National Assembly majority but faces a deeply polarized society. Conservative opposition, despite the martial law disgrace, retains roughly 40% base support. Business leaders need both Columbia technology access and Cathay market access. Political support sits at 35% — the honeymoon fading fast. Hanguk cannot afford to choose between its security guarantor and its largest economic partner, but the Trap is forcing exactly that choice.
$$ WHERE id = 'hanguk' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- LEVANTIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Levantia enters the simulation at war — and in its element. Operation Rising Lion, launched February 28, 2026, represents the culmination of decades of intelligence preparation against Persia's nuclear program. In coordination with Columbia's Operation Epic Fury, Levantia struck Persia's enrichment facilities, assassinated the previous Supreme Leader and senior officials, destroyed portions of the ballistic missile arsenal, and degraded early-warning systems. Over 3,000 targets struck in the first month. Simultaneously, Levantia launched operations in Lebanon against Persia's most capable proxy, killing over 1,000 and displacing nearly a million. This is the most operationally committed country in the simulation relative to its size.

Levantia's military capability is disproportionate to its 5-coin economy. The highest technology sector share in the simulation (32%) — cybersecurity, defense tech, AI, biotech. Six ground units (2 committed to Lebanon), 4 tactical air units (2 conducting the Persia campaign), the densest air defense per territory in the world (3 units of Iron Dome, David's Sling, and Arrow systems intercepting Persia's missile and drone barrages), and 1 naval unit. The undeclared nuclear capability — Level 1, estimated 80-90 warheads delivered by ballistic missiles and submarine-based second strike — is the elephant in the room. If Persia's nuclear program survived the strikes and approaches breakout, Levantia's calculus shifts from conventional to existential.

The wartime economy is under strain. GDP growth suppressed, defense spending consuming unprecedented share of output. Stability at 5 — functional but stressed. Political support at 52% — solid but not overwhelming. The wartime coalition masks deep political fractures that will resurface when fighting stops: judicial reform crisis suspended rather than resolved, ultra-Orthodox conscription issue simmering, tech sector exhausted by perpetual mobilization. If the war ends in clear victory, the prime minister is vindicated. If it grinds on without resolution, domestic politics resurface violently.

Columbia's backing is unconditional — for now. Joint operations, shared intelligence, coordinated strikes. The tightest military partnership in the simulation. But Levantia's survival depends on finishing what it started before Columbia's political will evaporates (the Persia war is deeply unpopular in Columbia), before Persia regroups, and before the world's patience runs out. The multi-front commitment (Persia, Lebanon, ongoing operations in three other theaters) with 14 military units total means every unit is spoken for. One setback — an air defense failure, a ground operation gone wrong, a nuclear development revealed — could shift the entire strategic calculus overnight.
$$ WHERE id = 'levantia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- MIRAGE
-- ============================================================================
UPDATE countries SET country_brief = $$
Mirage is the Gulf's financial superpower under fire — literally. The country that built its brand on stability, connectivity, and pragmatic deal-making is absorbing Persian missile strikes on its gleaming skyline while trying to preserve the commercial relationships that made it rich. Since February 28, 2026, Persia has launched 357 ballistic missiles, over 1,800 drone attacks, and 15 cruise missiles at Mirage targets. Nine killed, 166 injured, and — more consequentially — the illusion of Gulf invulnerability destroyed. Missiles falling near the financial district shattered the image that made this city a global hub for capital, tourism, and talent. The economic damage from perception may exceed the physical damage from explosions.

The "no enemies" strategy that defined Mirage's foreign policy has been shattered by the Persia war. Columbia approved an $8.4 billion weapons package — drones, missiles, radar, F-16s. Mirage buys from everyone: Gallia's Rafale fighters, Columbia's THAAD, Cathay's drones, Levantia's defense technology. The 5-coin GDP understates Mirage's weight — massive sovereign wealth (ADIA at approximately $1 trillion, Mubadala at $300 billion) makes it the wealthiest country per capita in the simulation, with 15 coins starting treasury and zero sovereign debt.

Mirage's deeper strategic value lies in connectivity. The financial district is the world's waystation — a place where sanctioned Sarmatian money, Cathay Belt and Road investments, Western venture capital, and Gulf sovereign wealth all flow through the same institutions. This makes Mirage indispensable to everyone and fully trusted by no one. The unique Financial Intermediary mechanic reflects this: sanctions imposed by any country are 20% more effective when Mirage cooperates with enforcement (Mirage sees the financial flows), and 20% more effective at evasion when routed through Mirage (Mirage enables the workarounds). Per sanction, per round, Mirage chooses whether to enforce or enable.

The BRICS+ membership, cryptocurrency regulatory frameworks, and financial innovation agenda signal Mirage's bet on a multipolar financial future. But the Abraham Accords with Levantia, the Columbia arms dependency, and the Gulf security architecture keep Mirage firmly in the Western orbit for defense. Military capability is modest (2 ground, 1 naval, 2 tactical air, 2 air defense) but the air defense systems have been tested in combat against Persian barrages. Stability at 8 and political support at 70% reflect authoritarian prosperity — but if the skyline keeps getting hit and capital flees, the social contract frays. The country that wanted no enemies now has one across the Gulf with nothing to lose.
$$ WHERE id = 'mirage' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- PHRYGIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Phrygia is the ultimate swing state — a Western Treaty member that buys Sarmatia air defense systems, a BRICS+ observer that hosts the alliance summit, a mediator in the Ruthenia war that profits from both sides, and a country whose president has turned strategic ambiguity into a personal art form. President Vizier has governed for over two decades, concentrating power in a presidential system that makes foreign policy intensely personal. The result: a country everyone needs for something and nobody trusts for anything. Columbia needs the Bosphorus and the alliance's southern flank. Sarmatia needs energy transit routes and sanctions workarounds. Cathay needs an alliance insider. The Ereb Union needs migration management. Gulf states need a power broker.

The Bosphorus Strait is Phrygia's trump card. The only passage between the Black Sea and the Mediterranean, controlled under international convention with legal authority to restrict warship transit during wartime. This gives Phrygia the ability to block Sarmatia naval access (or allow it), leverage over the Ruthenia conflict, and bargaining power with every maritime nation that needs Black Sea access. The strait control card can be played once per round as a diplomatic lever.

The economy is the constraint that drives the dealing. Inflation at 45% — the highest in the simulation among non-collapsed states, down from a peak above 75%. The lira has lost most of its value against the dollar over the past decade. GDP of 11 coins with 3% growth sounds respectable but is devastating in real purchasing power. Unorthodox economic policies created the crisis; the belated return to orthodoxy is producing painful correction. Gulf investment and Sarmatia energy deals keep the economy afloat. Foreign policy flexibility is partly a function of economic desperation — Phrygia cannot afford to alienate any source of capital. The trade deficit of 3 coins and debt burden of 3 coins per round against a 4-coin treasury leave almost no fiscal cushion.

Militarily, Phrygia fields the second-largest Western Treaty force by personnel: 6 ground units, 2 naval, 3 tactical air, 1 air defense. The domestic defense industry is a genuine success — Bayraktar drones are an export hit, and warship production is competitive. Phrygia supplied drones to Ruthenia while buying S-400 systems from Sarmatia — the purchase that cost access to the F-35 program. The Syria dimension adds depth: following the regime change, Phrygia has secured $11 billion in energy and infrastructure contracts, positioning as an energy hub connecting Caspian gas, Gulf LNG, and European markets. The Persia war complicates everything — missiles were shot down over Phrygia's territory, the shared border means refugee flows and energy disruption, and involuntary involvement in a conflict serving no Phrygian interest. Stability at 5 and political support at 50% reflect a hybrid regime under permanent economic stress with no succession mechanism — Vizier IS the system.
$$ WHERE id = 'phrygia' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- SOLARIA
-- ============================================================================
UPDATE countries SET country_brief = $$
Solaria is the world's energy pricing superpower under direct military threat for the first time in a generation. Crown Prince Wellspring — young, ambitious, transformational, and ruthless — has spent a decade remaking the kingdom: social liberalization, tourism megaprojects, and a $1 trillion Vision 2030 diversification program built on the bet that oil wealth now can build a post-oil economy before the wells run dry. That bet is under unprecedented stress.

When Columbia and Levantia struck Persia on February 28, 2026, the retaliatory missile barrage hit Solaria's oil infrastructure directly. The Ras Tanura refinery — one of the world's largest — went into partial shutdown. For the first time in history, Persia attacked all six Gulf states simultaneously. Solaria raised military readiness to maximum. The kingdom that cultivated "no enemies" diplomacy is now hosting the air war against its neighbor across the Gulf, with Columbia troops on its soil.

Every country's economic health depends on oil prices, and Solaria controls the tap. As the Cartel's de facto leader with roughly 2 million barrels per day of spare capacity — over 50% of the global strategic reserve — Solaria's production decisions reshape the global economy. The fiscal breakeven is approximately $81 per barrel. Current prices are slightly above that, with the Persia war disruption keeping them elevated. The production dial is the single most consequential economic lever any solo country possesses. GDP of 11 coins, 3.5% growth, massive trade surplus of 8 coins, and 20 coins starting treasury (backed by the sovereign wealth fund at approximately $930 billion) make Solaria one of the wealthiest players in the simulation.

The hedging strategy remains intact despite the war. BRICS+ membership signals multipolarity. Cathay buys a quarter of crude exports and provides technology Columbia will not share. Sarmatia is an OPEC+ partner. Bharata is a growing energy customer. Wellspring has stated publicly that Solaria will develop nuclear weapons if Persia acquires them — the nuclear proliferation question looms over every outcome of the Persia war. The military — 3 ground, 1 naval, 3 tactical air, 2 air defense — is professional but combat-untested, equipped with Columbia systems whose Patriot batteries were tested against Persian missile barrages with mixed results. Wellspring has concentrated power more completely than any ruler in modern history, eliminating rival princes. This means fast decisions but no institutional brake if he miscalculates. If oil facilities are destroyed and the economy contracts, the social contract — prosperity in exchange for political quiescence — frays at its foundation.
$$ WHERE id = 'solaria' AND sim_run_id = '00000000-0000-0000-0000-000000000001';

-- ============================================================================
-- YAMATO
-- ============================================================================
UPDATE countries SET country_brief = $$
Yamato is quietly undergoing its most significant military transformation since 1945 — a Pacific democracy with 43 coins GDP (fourth-largest economy), the world's second-largest foreign exchange reserves ($1.2 trillion), and a defense buildup that has achieved the 2% GDP spending target two years ahead of schedule under Cathay anxiety and Columbia pressure. The record defense budget funds standoff missiles with 1,000km range, next-generation fighter jets (jointly developed with Albion and Ponte for 2035), unmanned systems, and integrated missile defense. Yamato is building the capacity to strike Cathay's coastal military infrastructure — a capability that was politically unthinkable a decade ago.

The nuclear dimension is latent but real. Yamato possesses the technical infrastructure — advanced reactors, plutonium stockpiles, missile technology, and scientific expertise — to develop nuclear weapons within an estimated three years. The prime minister has publicly discussed relaxing the non-nuclear principles. This "latent capability" is a strategic signal that shapes every calculation in the Pacific. Whether Yamato would go nuclear — and at what cost to the Columbia alliance — is one of the simulation's most consequential questions.

Columbia's main Pacific base sits on Yamato's territory: ground forces, tactical air, air defense — the hub that makes Formosa deterrence possible. Yamato hosts 54,000 Columbia personnel. The alliance is the cornerstone of Pacific security, but Columbia's transactional approach under Dealer raises the question every strategist fears: what if Columbia does not come? Yamato is remilitarizing because it no longer fully trusts the protection. The 0.55 Formosa semiconductor dependency is the highest in the simulation outside Formosa itself — if those fabs are destroyed, Yamato's electronics industry collapses.

The structural weakness is demographic. Births have fallen for the tenth consecutive year. The population is aging and shrinking with a median age above 48. GDP has stagnated for decades despite massive accumulated wealth. Debt-to-GDP at 260% is the highest in the world, though almost entirely domestically held and denominated in yen. Social spending at 30% for the aging population is growing every year and politically untouchable. The military transformation — 3 ground, 4 naval (including the most capable Pacific fleet outside Columbia), 3 tactical air, 2 air defense — represents quality over quantity. Stability at 8, the highest in the simulation, reflects mature democratic institutions and social cohesion. But Japan's deep pacifist instincts — a gap between intellectual acceptance of rearmament and emotional readiness for conflict — could close overnight if Cathay moves on Formosa. Until then, the transformation proceeds incrementally, anxiously, and with growing independence.
$$ WHERE id = 'yamato' AND sim_run_id = '00000000-0000-0000-0000-000000000001';
